# Generated by Django 5.2.10 on 2026-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhaar number (12 digits)', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cin_number',
            field=models.CharField(blank=True, help_text='CIN — Corporate Identification Number (21 chars)', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Legal registered company name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary point of contact at the company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit extended to this customer (₹)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment due within N days', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation of the contact person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of employees', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN — 15-character alphanumeric', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g. IT, Manufacturing, Education', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, not shown to customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN — 10-character alphanumeric', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number_individual',
            field=models.CharField(blank=True, help_text='PAN for individual customers', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='tan_number',
            field=models.CharField(blank=True, help_text='TAN — Tax Deduction Account Number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='trade_name',
            field=models.CharField(blank=True, help_text='Trade name if different from legal name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='udyam_number',
            field=models.CharField(blank=True, help_text='Udyam Registration Number for MSMEs', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], db_index=True, max_length=20),
        ),
    ]
