# Generated by Django 5.2.10 on 2026-04-15 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options_remove_customer_identifiers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('PROFILE_UPDATED', 'Profile Updated'), ('DEACTIVATED', 'Customer Deactivated'), ('REACTIVATED', 'Customer Reactivated'), ('RENTAL_OUT', 'Laptop Rented Out'), ('RENTAL_RETURNED', 'Rental Returned'), ('RENTAL_REPLACED', 'Rental Replaced'), ('DEMO_OUT', 'Demo Assigned'), ('DEMO_RETURNED', 'Demo Returned'), ('DEMO_CONVERTED', 'Demo Converted'), ('SALE', 'Laptop Sold'), ('SALE_RETURNED', 'Sale Returned')], db_index=True, max_length=30)),
                ('laptop_name', models.CharField(blank=True, max_length=200)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_label', models.CharField(blank=True, help_text='e.g. R-12, D-5, S-8', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer History',
                'verbose_name_plural': 'Customer Histories',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
