# Generated by Django 5.2.10 on 2026-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict, help_text='Key fields from the source record frozen at event time (dates, totals, item count, etc.)'),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='snapshot_status',
            field=models.CharField(blank=True, help_text='Status of the Rental/Demo/Sale at the time of this event (e.g. ONGOING, RETURNED)', max_length=50),
        ),
    ]
