# Generated by Django 5.2.10 on 2026-02-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalreturn_created_at_rentalreturn_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalreturn',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='rentals.rental'),
        ),
    ]
