# Generated by Django 5.2.10 on 2026-01-29 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_is_active_alter_customer_created_by_and_more'),
        ('inventory', '0004_laptop_created_at_laptop_created_by_and_more'),
        ('rentals', '0003_remove_rental_is_active_alter_rental_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='end_date',
            new_name='actual_return_date',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='start_date',
            new_name='expected_return_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='extra_details',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='security_amount',
        ),
        migrations.AddField(
            model_name='rental',
            name='rent_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='inventory.laptop'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('RETURNED', 'Returned')], default='ONGOING', max_length=20),
        ),
    ]
