# Generated by Django 5.2.10 on 2026-02-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_specs_laptop_description_and_more'),
        ('rentals', '0003_alter_rentalreturn_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='rentalreturn',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='rentalreplacement',
            name='new_laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_laptop', to='inventory.laptop'),
        ),
        migrations.AlterField(
            model_name='rentalreplacement',
            name='old_laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_laptop', to='inventory.laptop'),
        ),
        migrations.AlterField(
            model_name='rentalreturn',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
