# Generated by Django 5.2.10 on 2026-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rename_end_date_rental_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
