# Generated by Django 5.2.10 on 2026-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_rental_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalreturn',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='rentalreturn',
            name='rental',
        ),
        migrations.AddField(
            model_name='rental',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='RentalReplacement',
        ),
        migrations.DeleteModel(
            name='RentalReturn',
        ),
    ]
