# Generated by Django 5.2.10 on 2026-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_rentalreturn_laptop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='discount',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
