# Generated by Django 5.2.10 on 2026-02-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_updated_at'),
        ('inventory', '0006_rename_specs_laptop_description_and_more'),
        ('rentals', '0006_remove_rental_discount_rentalitem_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='expected_return_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rent_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='rental',
            name='parent_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rentals.rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.laptop'),
        ),
    ]
