# Generated by Django 5.2.10 on 2026-03-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_laptop_gpu'),
        ('rentals', '0008_rental_actual_return_date_rental_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_asset_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_condition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_display',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_generation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_gpu',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_processor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_purchased_from',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_rent_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_storage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.laptop'),
        ),
    ]
