# Generated by Django 5.2.10 on 2026-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rentalitem_snapshot_asset_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='snapshot_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
