# Generated by Django 5.2.10 on 2026-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_add_snapshot_customer_name_to_rentalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='expected_return_date',
        ),
    ]
