# Generated by Django 5.2.10 on 2026-01-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_laptop_is_active_alter_laptop_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laptop',
            unique_together={('brand', 'model', 'serial_number')},
        ),
        migrations.AlterField(
            model_name='laptop',
            name='specs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('SCRAP', 'Scrap')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Returned'), ('DAMAGE', 'Damaged')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.laptop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='extra_details',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='updated_by',
        ),
    ]
