# Generated by Django 5.2.10 on 2026-02-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_laptop_created_at_laptop_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='i5', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(default='8GB', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(default='256GB', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('SCRAP', 'Scrap'), ('DEMO', 'Demo')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
