# Generated by Django 5.2.10 on 2026-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_laptop_price_laptop_processor_laptop_ram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='specs',
            new_name='description',
        ),
        migrations.AddField(
            model_name='laptop',
            name='rent_per_month',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
