# Generated by Django 5.2.10 on 2026-03-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_updated_at'),
        ('inventory', '0006_rename_specs_laptop_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_laptops', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
