# Generated by Django 5.2.10 on 2026-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_laptop_customer_laptop_purchased_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='generation',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
