# Generated by Django 5.2.10 on 2026-03-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_updated_at'),
        ('inventory', '0009_alter_laptop_options_laptop_asset_tag_laptop_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='laptop',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_size',
            field=models.CharField(blank=True, help_text='e.g. 15.6 inch', max_length=20),
        ),
        migrations.AddField(
            model_name='laptop',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(blank=True, help_text='e.g. Windows 11 Pro', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='asset_tag',
            field=models.CharField(blank=True, default=1, help_text='Internal asset tag e.g. LT-0001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('DEMO', 'Demo'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETURNED_TO_SUPPLIER', 'Returned to Supplier'), ('WRITTEN_OFF', 'Written Off')], default='AVAILABLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out — Rental'), ('RETURN', 'Returned by Customer'), ('SOLD', 'Sold'), ('MAINTENANCE_OUT', 'Sent for Maintenance'), ('MAINTENANCE_IN', 'Returned from Maintenance'), ('SUPPLIER_RETURN', 'Returned to Supplier'), ('WRITTEN_OFF', 'Written Off')], max_length=20),
        ),
        migrations.CreateModel(
            name='LaptopHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(choices=[('ADDED', 'Added to Inventory'), ('RENTED_OUT', 'Rented Out'), ('RETURNED', 'Returned by Customer'), ('SOLD', 'Sold'), ('SENT_FOR_MAINTENANCE', 'Sent for Maintenance'), ('MAINTENANCE_DONE', 'Maintenance Done'), ('RETURNED_TO_SUPPLIER', 'Returned to Supplier'), ('WRITTEN_OFF', 'Written Off'), ('STATUS_CHANGED', 'Status Changed'), ('SPECS_UPDATED', 'Specs Updated')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Rental ID / Sale ID / etc.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.laptop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='inventory.supplier'),
        ),
    ]
