# Generated by Django 5.2.10 on 2026-03-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_laptop_options_laptop_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='cost_to_company',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
