# Generated by Django 5.2.10 on 2026-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_laptop_cost_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(blank=True, help_text='e.g. NVIDIA GeForce RTX 4060, Intel Iris Xe, AMD Radeon RX 7600M', max_length=150, verbose_name='GPU / Graphics Card'),
        ),
    ]
