# Generated by Django 5.2.10 on 2026-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_laptop_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out — Rental'), ('RETURN', 'Returned by Customer'), ('SOLD', 'Sold'), ('MAINTENANCE_OUT', 'Sent for Maintenance'), ('MAINTENANCE_IN', 'Returned from Maintenance'), ('SUPPLIER_RETURN', 'Returned to Supplier'), ('WRITTEN_OFF', 'Written Off'), ('DEMO_OUT', 'Assigned for Demo'), ('DEMO_RETURN', 'Returned from Demo')], max_length=20),
        ),
    ]
