# Generated by Django 5.2.10 on 2026-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockmovement_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='remark',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('RETURN', 'Return'), ('ADJUST', 'Adjust')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
