# Generated by Django 5.2.10 on 2026-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockmovement_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
