# Generated by Django 5.2.10 on 2026-03-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_laptop_generation'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RENTAL', 'Rental'), ('CUSTOM', 'Custom')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.laptop'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20),
        ),
    ]
