# Generated by Django 5.2.10 on 2026-03-23 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_options_remove_customer_identifiers_and_more'),
        ('inventory', '0011_laptop_cost_to_company'),
        ('rentals', '0008_rental_actual_return_date_rental_created_by_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('RETURNED', 'Returned'), ('CONVERTED_RENTAL', 'Converted to Rental'), ('CONVERTED_SALE', 'Converted to Sale')], default='ONGOING', max_length=20)),
                ('purpose', models.CharField(choices=[('performance_testing', 'Performance Testing'), ('software_compatibility', 'Software Compatibility'), ('team_evaluation', 'Team Evaluation'), ('student_trial', 'Student Trial'), ('video_editing', 'Video Editing'), ('programming_development', 'Programming / Development'), ('graphic_design', 'Graphic Design'), ('general_evaluation', 'General Evaluation'), ('other', 'Other')], default='general_evaluation', max_length=50)),
                ('specific_requirements', models.TextField(blank=True)),
                ('requires_training', models.BooleanField(default=False)),
                ('delivery_required', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('feedback_received', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('converted_rental', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_demo', to='rentals.rental')),
                ('converted_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_demo', to='sales.sale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demo.demo')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.laptop')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('demo', 'laptop')},
            },
        ),
    ]
