# Generated by Django 5.2.10 on 2026-03-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options_remove_customer_identifiers_and_more'),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demos', to='customers.customer'),
        ),
    ]
