# Generated by Django 5.2.10 on 2026-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_add_snapshot_fields_to_demoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='expected_return_date',
        ),
    ]
