# Generated by Django 5.2.10 on 2026-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_module_365bd8_idx',
            old_name='audit_module_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_54788b_idx',
            old_name='audit_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_19e18a_idx',
            old_name='audit_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, help_text='List of field names that changed', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Any additional context (endpoint, params, etc.)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, help_text='State of the object AFTER the change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, help_text='State of the object BEFORE the change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, help_text='PK of the affected object (as string)', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_repr',
            field=models.CharField(blank=True, help_text='Human-readable label for the affected object', max_length=500),
        ),
    ]
